import Sidebar from "../components/Sidebar";
import { Flex, Box, Divider, Center } from "@chakra-ui/react";
import Head from "next/head";

export async function getStaticProps() {
  const allCategoriesPeliculas = await contentful.getCategoriesPeliculas();
  const data = allCategoriesPeliculas;
  console.log(data);
  return {
    props: {
      data,
    },
  };
}

const MainLayout = ({ children, data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>TO SEE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="row">
        <Sidebar />
        <Center height="100vh">
          <Divider orientation="vertical" />
        </Center>
        <Box py={"20px"} w="80vw">
          {children}
        </Box>
      </Flex>
    </>
  );
};

export default MainLayout;
