import Head from "next/head";
// import Image from 'next/image'
import Layout from "../layouts/MainLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Videojuegos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Enciclopedia</h1>
      </Layout>
    </div>
  );
}
